name: feelworld_tally
description: A camera tally app for the Feelworld live mixers.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  wakelock: ^0.6.2
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
